version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
  build:
    commands:
      - echo Building Docker image...
      - docker build -t my-app .
      - docker tag batch-job:latest $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/batch-job:latest
  post_build:
    commands:
      - echo Pushing Docker image...
      - docker push $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/batch-job:latest
artifacts:
  files:
    - '**/*'
